### ISSUE TITLE
Module incompatible with Terraform 0.12

### ISSUE THREAD

**Issue by ghost** [traveloka/terraform-aws-waf-webacl-supporting-resources#11]
I ran this module against Terraform 12 and it fails. See below. 

on .terraform\modules\owasp_top_10\traveloka-terraform-aws-waf-owasp-top-10-rules-8933a71\outputs.tf line 21, in output "04_paths_rule_id":
  21: output "04_paths_rule_id" {

A name must start with a letter and may contain only letters, digits,
underscores, and dashes.

**Comment by rafikurnia** [comment]
Hi @ghost
Thanks for submitting an issue. Unfortunately you opened it in the wrong place. 
Regarding this issue, yes we are discussing about it at traveloka/terraform-aws-waf-owasp-top-10-rules#9 and traveloka/terraform-aws-waf-owasp-top-10-rules#10
