### ISSUE TITLE
Error changing names and metrics name according to requirement

### ISSUE THREAD

**Issue by amolkhanorkar** [traveloka/terraform-aws-waf-webacl-supporting-resources#7]
@rafikurnia 
I am getting error while provisioning resources and changing "names", "metric names", "product_domain", "service name" according to my requirements but it is giving error for creating rules as they are referring modules. 

Please help me solving this issue. I will post the error once I reproduce it again.

**Comment by rafikurnia** [comment]
Hi @amolkhanorkar, thanks for reporting the issue you have encountered. It would be nice if you could provide data, e.g., parameters you inputted. Without them, I am afraid I can't help you at. 

So thank you, I look forward to seeing the errors if you able to reproduces them again.

**Comment by rafikurnia** [comment]
Hi @amolkhanorkar 
It is been a while since the last time we hear from you.
I assume you are not facing the issue anymore.
Thanks
